apiVersion: apps/v1
kind: Deployment
metadata:
  name: flip-deployment
  labels:
    app: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart-cont
        image: sreeja026/flip-image:v1
        ports:
        - containerPort: 80
